import type { City, ProfileStatus, Sector, Skill } from "@/lib/vocabulary";

export interface SeedProfile {
  name: string;
  email: string;
  birthDate: string;
  title: string;
  sector: Sector;
  city: City;
  skills: Skill[];
  score: number;
  videoUrl: string;
  bio: string;
  views: number;
  contactCount: number;
  status: ProfileStatus;
}

export const SEED_PROFILES: SeedProfile[] = [
  {
    name: "Amina Berthier",
    email: "amina@exemple.fr",
    birthDate: "1991-04-17",
    title: "Chargée de relation client",
    sector: "Commerce",
    city: "Lyon",
    skills: ["Relation client", "Communication", "Adaptabilité"],
    score: 82,
    videoUrl: "https://youtube.com/watch?v=jeb-amina",
    bio: "Sept ans en boutique et en centre d'appels. Je cherche un poste où la relation client est un métier à part entière, pas une case du planning.",
    views: 214,
    contactCount: 6,
    status: "published",
  },
  {
    name: "Karim Vasseur",
    email: "karim.vasseur@exemple.fr",
    birthDate: "1988-11-03",
    title: "Préparateur de commandes",
    sector: "Logistique",
    city: "Lille",
    skills: ["Rigueur", "Autonomie", "Travail en équipe"],
    score: 74,
    videoUrl: "https://vimeo.com/jeb-karim",
    bio: "Entrepôt, inventaire, cariste 1-3-5. Je sais tenir une cadence sans casser la marchandise ni l'ambiance.",
    views: 168,
    contactCount: 4,
    status: "published",
  },
  {
    name: "Sonia Delaunay-Frey",
    email: "sonia.delaunay@exemple.fr",
    birthDate: "1984-06-25",
    title: "Développeuse front-end",
    sector: "Numérique",
    city: "Nantes",
    skills: ["Gestion de projet", "Autonomie", "Communication"],
    score: 91,
    videoUrl: "https://youtube.com/watch?v=jeb-sonia",
    bio: "Reconversion réussie après dix ans en librairie. Je code des interfaces accessibles et je documente ce que je livre.",
    views: 402,
    contactCount: 11,
    status: "published",
  },
  {
    name: "Mathieu Ozanne",
    email: "mathieu.ozanne@exemple.fr",
    birthDate: "1995-02-09",
    title: "Aide-soignant",
    sector: "Santé",
    city: "Marseille",
    skills: ["Adaptabilité", "Travail en équipe", "Rigueur"],
    score: 0,
    videoUrl: "https://youtube.com/watch?v=jeb-mathieu",
    bio: "EHPAD puis service de gériatrie. Je cherche un établissement qui laisse le temps de faire les choses correctement.",
    views: 96,
    contactCount: 2,
    status: "published",
  },
  {
    name: "Fatou Nguyen",
    email: "fatou.nguyen@exemple.fr",
    birthDate: "1990-09-14",
    title: "Assistante de direction",
    sector: "Éducation",
    city: "Paris",
    skills: ["Organisation", "Communication", "Rigueur"],
    score: 88,
    videoUrl: "https://vimeo.com/jeb-fatou",
    bio: "Secrétariat de rectorat pendant six ans. Agenda, comptes rendus, gestion de crise du lundi matin.",
    views: 311,
    contactCount: 9,
    status: "published",
  },
  {
    name: "Tristan Lebel",
    email: "tristan.lebel@exemple.fr",
    birthDate: "2009-03-22",
    title: "Électricien du bâtiment",
    sector: "Bâtiment",
    city: "Bordeaux",
    skills: ["Autonomie", "Rigueur"],
    score: 0,
    videoUrl: "https://youtube.com/watch?v=jeb-tristan",
    bio: "Chantiers neufs et rénovation. Habilitations B1V-BR à jour. Je préfère les équipes petites et les chantiers propres.",
    views: 74,
    contactCount: 1,
    status: "published",
  },
  {
    name: "Leïla Amrani",
    email: "leila.amrani@exemple.fr",
    birthDate: "1993-12-01",
    title: "Conductrice de ligne",
    sector: "Industrie",
    city: "Strasbourg",
    skills: ["Rigueur", "Travail en équipe", "Organisation"],
    score: 79,
    videoUrl: "https://vimeo.com/jeb-leila",
    bio: "Agroalimentaire, 3x8. Je forme les nouveaux arrivants depuis quatre ans et j'aimerais que ça devienne mon poste.",
    views: 132,
    contactCount: 3,
    status: "published",
  },
  {
    name: "Pierre-Yves Caron",
    email: "pierre-yves.caron@exemple.fr",
    birthDate: "1979-07-30",
    title: "Technicien support",
    sector: "Numérique",
    city: "Toulouse",
    skills: ["Relation client", "Adaptabilité", "Autonomie"],
    score: 71,
    videoUrl: "https://youtube.com/watch?v=jeb-pierre",
    bio: "Support niveau 2, parc de 900 postes. Je traduis les problèmes techniques en phrases que les gens comprennent.",
    views: 187,
    contactCount: 5,
    status: "published",
  },
  {
    name: "Marion Estève",
    email: "marion.esteve@exemple.fr",
    birthDate: "1997-05-12",
    title: "Éducatrice de jeunes enfants",
    sector: "Éducation",
    city: "Lyon",
    skills: ["Communication", "Organisation", "Adaptabilité"],
    score: 85,
    videoUrl: "https://vimeo.com/jeb-marion",
    bio: "Crèche associative puis multi-accueil municipal. Je cherche une structure avec un vrai projet pédagogique.",
    views: 205,
    contactCount: 7,
    status: "published",
  },
  {
    name: "Yann Kervella",
    email: "yann.kervella@exemple.fr",
    birthDate: "1986-10-08",
    title: "Magasinier cariste",
    sector: "Logistique",
    city: "Nantes",
    skills: ["Autonomie", "Rigueur"],
    score: 0,
    videoUrl: "https://youtube.com/watch?v=jeb-yann",
    bio: "Quinze ans de quai. Je connais les flux, les erreurs de picking et comment les éviter.",
    views: 61,
    contactCount: 0,
    status: "published",
  },
  {
    name: "Nadia Chevallier",
    email: "nadia.chevallier@exemple.fr",
    birthDate: "1992-01-26",
    title: "Vendeuse conseil",
    sector: "Commerce",
    city: "Paris",
    skills: ["Relation client", "Communication"],
    score: 68,
    videoUrl: "https://vimeo.com/jeb-nadia",
    bio: "Prêt-à-porter et cosmétique. Je vends sans forcer, ça revient plus souvent.",
    views: 143,
    contactCount: 3,
    status: "published",
  },
  {
    name: "Olivier Ranucci",
    email: "olivier.ranucci@exemple.fr",
    birthDate: "1975-08-19",
    title: "Chef de projet junior",
    sector: "Numérique",
    city: "Marseille",
    skills: ["Gestion de projet", "Organisation", "Communication"],
    score: 0,
    videoUrl: "https://youtube.com/watch?v=jeb-olivier",
    bio: "Deux ans en agence, un an en freelance. Je cadre, je planifie, je relance.",
    views: 88,
    contactCount: 1,
    status: "pending",
  },
  {
    name: "Claire Bonnefoy",
    email: "claire.bonnefoy@exemple.fr",
    birthDate: "1999-03-05",
    title: "Infirmière",
    sector: "Santé",
    city: "Lille",
    skills: ["Rigueur", "Adaptabilité", "Travail en équipe"],
    score: 93,
    videoUrl: "https://vimeo.com/jeb-claire",
    bio: "Urgences puis bloc. Je cherche un poste de jour, en clinique ou en libéral.",
    views: 356,
    contactCount: 12,
    status: "published",
  },
  {
    name: "Sébastien Marchal",
    email: "sebastien.marchal@exemple.fr",
    birthDate: "1983-11-21",
    title: "Conducteur de travaux",
    sector: "Bâtiment",
    city: "Toulouse",
    skills: ["Gestion de projet", "Autonomie", "Rigueur"],
    score: 0,
    videoUrl: "https://youtube.com/watch?v=jeb-sebastien",
    bio: "Gros œuvre, marchés publics. Je tiens un planning et je le fais tenir aux autres.",
    views: 119,
    contactCount: 2,
    status: "pending",
  },
];
